ignore:
  - "**/cmd/**/main.go"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

comment:
  layout: "header,diff,flags,files"
  behavior: default
